//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPlannerLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportation : TripItem
    {
        public int Id { get; set; }
        public int TripId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }

        public string Origin { get; set; }

        public string Destination { get; set; }
    
        public virtual Trip Trip { get; set; }

        public override string ToString()
        {
            return "Transportation: " + "Start: " + this.StartTime.ToString("MM/dd/yyyy h:mm tt") + ", End: " + this.EndTime.ToString("MM/dd/yyyy h:mm tt") + " Origin:" + Origin + " Destination: " + Destination;
        }
    }
}
