//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPlannerLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.Waypoints = new HashSet<Waypoint>();
        }
    
        public int Id { get; set; }
        public string Name {
            get { return this.Name; }
            set
            {
                if (String.IsNullOrEmpty(value))
                {
                    throw new ArgumentNullException("Trip must have a name");
                }
                this.Name = value;
            }
            }
        public System.DateTime StartDate
        {
            get { return this.StartDate; }
            set
            {
                if (value <= DateTime.Now)
                {

                    throw new ArgumentException("Start date must not be before today");
                }
                this.StartDate = value;
            }
        }
        public System.DateTime EndDate
        {
            get { return this.EndDate; }
            set
            {
                if (value <= this.StartDate)
                {

                    throw new ArgumentException("End date must not be before start date");
                }
                this.EndDate = value;
            }
        }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Waypoint> Waypoints { get; set; }
    }
}
