//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPlannerLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waypoint
    {
        public int Id { get; set; }
        public string Location { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public int TripId { get; set; }
        public string Description { get; set; }
    
        public virtual Trip Trip { get; set; }

        public override string ToString()
        {
            return "Waypoint: " + this.Location + ", Start: " + this.StartDateTime.ToString("MM/dd/yyyy h:mm tt") + ", End: " + this.EndDateTime.ToString("MM/dd/yyyy h:mm tt");
        }

    }
}
